import Head from 'next/head';
import LeftNavBar from '../components/LeftNavBar';
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LeftNavBar/>
        <p>Home Page</p>

        <Link href="/one">Link To Other Page</Link><br/><br/>
        <Link href="/two">two</Link>
      </main>
    </>
  )
}
